name: urban_match_task
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flutter_spinkit: ^5.2.1
  go_router: ^15.1.3
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  google_maps_flutter: ^2.12.2
  intl: ^0.20.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_theme/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
